hw/nxagent/NX*.c: Amend re-introduced nxagent warnings by fixing the corresponding code section in files included from "somewhere" in nx-X11/programs/Xserver/.
 (1)
 In file included from NXrender.c:44:0:
 ../../mi/../render/render.c: In function ‘swapStops’:
 ../../mi/../render/render.c:2541:13: warning: variable ‘colors’ set but not used [-Wunused-but-set-variable]
      CARD16 *colors;
              ^

 (2)
 In file included from NXevents.c:133:0:
 ../../dix/events.c: In function ‘ReinitializeRootWindow’:
 ../../dix/events.c:2046:15: warning: unused variable ‘pScreen’ [-Wunused-variable]
      ScreenPtr pScreen = win->drawable.pScreen;
                ^
 ../../dix/events.c: In function ‘XineramaPointInWindowIsVisible’:
 ../../dix/events.c:2177:15: warning: variable ‘pScreen’ set but not used [-Wunused-but-set-variable]
      ScreenPtr pScreen = pWin->drawable.pScreen;
                ^
 In file included from NXevents.c:133:0:
 ../../dix/events.c: In function ‘XineramaPointInWindowIsVisible’:
 ../../dix/events.c:2191:2: error: ‘pScreen’ undeclared (first use in this function)
   pScreen = pWin->drawable.pScreen;
   ^

 (3)
 In file included from NXdixfonts.c:77:0:
 ../../dix/dixfonts.c: In function ‘GetFontPath’:
 ../../dix/dixfonts.c:1890:2: warning: return makes pointer from integer without a cast
   return BadAlloc;
   ^