replace extensions/xf86bigfont*.h by system header files
In order for this to work the following commit has been backported:

   From abf4e0b7e349b0238b2b97a16b8a308b5026af31 Mon Sep 17 00:00:00 2001
   From: Yaakov Selkowitz <yselkowitz@users.sourceforge.net>
   Date: Mon, 22 Mar 2010 00:44:28 -0500
   Subject: New header for XF86Bigfont server functions

   Xext/xf86bigfont.c contains three non-static functions which are called
   elsewhere in the server.  This creates a new header containing these
   declarations in order to fix several warnings:

   xf86bigfont.c:285: warning: no previous prototype for `XF86BigfontFreeFontShm'
   dixfonts.c:502: warning: implicit declaration of function `XF86BigfontFreeFontS$
   dixfonts.c:502: warning: nested extern declaration of `XF86BigfontFreeFontShm'
   log.c:436: warning: implicit declaration of function `XF86BigfontCleanup'
   log.c:436: warning: nested extern declaration of `XF86BigfontCleanup'

   Signed-off-by: Yaakov Selkowitz <yselkowitz@users.sourceforge.net>
   Reviewed-by: Julien Cristau <jcristau@debian.org>